### ISSUE TITLE
Dockerで動くようにする

### ISSUE THREAD

**Issue by smicle** [salmonella-team/discord-bot-cal#17]
k8sで動かしたい。

**Comment by smicle** [comment]
位置が悪くて動かないらしいので移動
https://github.com/salmonella-team/Discord_bot_cal/pull/15

**Comment by smicle** [comment]
名前が悪かったので変更
https://github.com/salmonella-team/Discord_bot_cal/pull/16

**Comment by s4m0r1** [comment]
Node-gypのビルドが失敗っぽくてそこらへん直さないといけない

**Comment by smicle** [comment]
一旦closeする
